### ISSUE TITLE
`FileNotFoundError: JSON path does not exist!` when parsing a demo

### ISSUE THREAD

**Issue by kostrykin** [pnxenopoulos/awpy#291]
## Describe the bug
Parsing a recent demo file yields `FileNotFoundError: JSON path does not exist!` Parsing other demos works.

## Include Information to Reproduce
```bash
wget http://replay192.valve.net/730/003636995971453288752_0322873614.dem.bz2
bzip2 -d 003636995971453288752_0322873614.dem.bz2
```
```python
import awpy
parser = awpy.parser.DemoParser(demofile='003636995971453288752_0322873614.dem', parse_rate=64, buy_style='csgo')
parser.parse()
```

```python
File /opt/csgo/env/lib/python3.9/site-packages/awpy/parser/demoparser.py:291, in DemoParser.parse(self, return_type, clean)
    277 """Wrapper for parse_demo() and read_json(). Use to parse a demo.
    278 
    279 Args:
   (...)
    288     AttributeError: Raises an AttributeError if the .json attribute is None
    289 """
    290 self.parse_demo()
--> 291 self.read_json(json_path=self.outpath + "/" + self.output_file)
    292 if clean:
    293     clean_data = self.clean_rounds()

File /opt/csgo/env/lib/python3.9/site-packages/awpy/parser/demoparser.py:262, in DemoParser.read_json(self, json_path)
    260 if not os.path.exists(json_path):
    261     self.logger.error("JSON path does not exist!")
--> 262     raise FileNotFoundError("JSON path does not exist!")
    264 # Read in json to .json attribute
    265 with open(json_path, encoding="utf8") as f:

FileNotFoundError: JSON path does not exist!
```

---

Output of `pip list`:
```
Package                Version
---------------------- -----------
aiohttp                3.8.1
aiosignal              1.2.0
argon2-cffi            21.3.0
argon2-cffi-bindings   21.2.0
asgiref                3.5.2
asttokens              2.0.8
async-timeout          4.0.2
attrs                  22.1.0
awpy                   1.2.3
backcall               0.2.0
beautifulsoup4         4.11.1
bleach                 5.0.1
cachetools             5.2.0
certifi                2022.6.15
cffi                   1.15.1
charset-normalizer     2.1.1
cloudpickle            2.2.0
csgo                   1.0.0
cycler                 0.11.0
debugpy                1.6.3
decorator              5.1.1
defusedxml             0.7.1
discord.py             2.0.1
Django                 4.1
doit                   0.36.0
entrypoints            0.4
executing              1.0.0
fastjsonschema         2.16.2
fonttools              4.37.1
frozenlist             1.3.1
gevent                 21.12.0
gevent-eventemitter    2.1
greenlet               1.1.3
gunicorn               20.1.0
idna                   3.3
imageio                2.21.2
importlib-metadata     4.12.0
ipykernel              6.15.3
ipython                8.5.0
ipython-genutils       0.2.0
jedi                   0.18.1
Jinja2                 3.1.2
jsonschema             4.16.0
jupyter_client         7.3.5
jupyter-core           4.11.1
jupyter-notebookparams 0.0.4
jupyterlab-pygments    0.2.2
jupyterlite            0.1.0b12
kiwisolver             1.4.4
lxml                   4.9.1
MarkupSafe             2.1.1
matplotlib             3.5.3
matplotlib-inline      0.1.6
mistune                2.0.4
mpmath                 1.3.0
multidict              6.0.2
nbclient               0.6.8
nbconvert              7.0.0
nbformat               5.5.0
nest-asyncio           1.5.5
networkx               2.8.6
notebook               6.4.12
numpy                  1.23.2
packaging              21.3
pandas                 1.4.4
pandocfilters          1.5.0
parso                  0.8.3
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 9.2.0
pip                    22.0.4
prometheus-client      0.14.1
prompt-toolkit         3.0.31
protobuf               3.20.1
psutil                 5.9.2
ptyprocess             0.7.0
pure-eval              0.2.2
pycparser              2.21
pycryptodomex          3.15.0
Pygments               2.13.0
pyparsing              3.0.9
pyrsistent             0.18.1
python-dateutil        2.8.2
pytz                   2022.2.1
pyzmq                  24.0.0
requests               2.28.1
scipy                  1.9.1
Send2Trash             1.8.0
setuptools             58.1.0
shapely                2.0.1
six                    1.16.0
soupsieve              2.3.2.post1
sqlparse               0.4.2
stack-data             0.5.0
steam                  1.3.0
sympy                  1.12
terminado              0.15.0
textdistance           4.4.0
tinycss2               1.1.1
tornado                6.2
tqdm                   4.64.0
traitlets              5.4.0
urllib3                1.26.12
vdf                    3.4
wcwidth                0.2.5
webencodings           0.5.1
yarl                   1.8.1
zipp                   3.8.1
zope.event             4.5.0
zope.interface         5.4.0
```

**Comment by JanEricNitschke** [comment]
First step should probably be to upgrade to the most recent awpy release of 1.3.1.

**Comment by JanEricNitschke** [comment]
When i run this i get this:

```
09:16:26 [INFO] Initialized awpy DemoParser with demofile D:\CSGO\ML\csgo\issue-291.dem
09:16:26 [INFO] Setting demo id to issue-291       
09:16:26 [INFO] Setting parse rate to 64
09:16:26 [INFO] Setting buy style to csgo
09:16:26 [INFO] Rollup damages set to False        
09:16:26 [INFO] Parse chat set to False
09:16:26 [INFO] Parse frames set to True
09:16:26 [INFO] Parse kill frames set to False     
09:16:26 [INFO] Output json indentation set to True
09:16:26 [INFO] Setting trade time to 5
09:16:26 [INFO] Setting buy style to csgo
09:16:26 [INFO] Go version>=1.18.0
09:16:26 [INFO] Running Golang parser from d:\CSGO\ML\csgo\awpy\parser\
09:16:26 [INFO] Looking for file at D:\CSGO\ML\csgo\issue-291.dem      
panic: invalid File-Type; expecting HL2DEMO in the first 8 bytes (ErrInvalidFileType)

goroutine 1 [running]:
main.checkError(...)
        d:/CSGO/ML/csgo/awpy/parser/parse_demo.go:2788
main.main()
        d:/CSGO/ML/csgo/awpy/parser/parse_demo.go:2636 +0x135f
exit status 2
09:16:28 [ERROR] No file produced, error in calling Golang
09:16:28 [ERROR] []
09:16:28 [ERROR] JSON path does not exist!
Traceback (most recent call last):
  File "d:\CSGO\ML\csgo\debugging.py", line 11, in <module>
    parser.parse()
  File "d:\CSGO\ML\csgo\awpy\parser\demoparser.py", line 592, in parse
    self.read_json(json_path=self.output_file)
  File "d:\CSGO\ML\csgo\awpy\parser\demoparser.py", line 551, in read_json
    raise FileNotFoundError(msg)
FileNotFoundError: JSON path does not exist!
```

Where especially this line:
`panic: invalid File-Type; expecting HL2DEMO in the first 8 bytes (ErrInvalidFileType)`
indicates that the demo file itself is just corrupted. I can also not open this in the game itself and the size of the demo file seems unusually small.

**Comment by JanEricNitschke** [comment]
I would close this issue now. But feel free to reopen if you need any more help or have any new info.
