### ISSUE TITLE
Error: could not create a new DataFrame

### ISSUE THREAD

**Issue by martin1896** [pnxenopoulos/awpy#350]
I'm getting an "could not create a new DataFrame" Error while parsing a demo. It happens at every attempt to parse any demo I have (pro match and pov). It's my first try to use your framework, so it's probably more of a wrong usage or something like that.

Using the following code:
from awpy import Demo
dem = Demo("ancient.dem", verbose=True, ticks=True)

2024-08-13 19:27:50.582 | SUCCESS  | awpy.demo:_success:151 - Created parser for ancient.dem
2024-08-13 19:27:50.824 | DEBUG    | awpy.demo:_debug:169 - Found the following game events: ['player_spawn', 'flashbang_detonate', 'inferno_expire', 'chat_message', 'hltv_chase', 'round_freeze_end', 'server_message', 'player_ping', 'bomb_dropped', 'bomb_planted', 'round_announce_match_point', 'hltv_versioninfo', 'bomb_defused', 'round_announce_last_round_half', 'player_ping_stop', 'cs_round_start_beep', 'weapon_fire', 'player_sound', 'cs_round_final_beep', 'hegrenade_detonate', 'vote_cast', 'hltv_fixed', 'server_cvar', 'inferno_startburn', 'player_given_c4', 'item_pickup', 'round_time_warning', 'announce_phase_end', 'smokegrenade_detonate', 'player_hurt', 'cs_win_panel_match', 'bomb_pickup', 'player_death', 'entity_killed', 'round_end_upload_stats', 'player_disconnect', 'cs_intermission', 'bomb_exploded', 'player_team', 'smokegrenade_expired', 'cs_pre_restart', 'round_announce_match_start', 'round_officially_ended']

thread '<unnamed>' panicked at src/lib.rs:761:77:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'polars.exceptions.ShapeError'>, value: ShapeError('could not create a new DataFrame: series "column_0" has length 3 while series "column_3" has length 64'), traceback: Some(<traceback object at 0x13a308340>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/username/dev/demoparser/test.py", line 17, in <module>
    dem = Demo("ancient.dem", verbose=False, ticks=True)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/awpy/demo.py", line 135, in __init__
    self._parse_demo()
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/awpy/demo.py", line 183, in _parse_demo
    self.parser.parse_events(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'polars.exceptions.ShapeError'>, value: ShapeError('could not create a new DataFrame: series "column_0" has length 3 while series "column_3" has length 64'), traceback: Some(<traceback object at 0x13a308340>) }

Disclaimer: I'm not an experienced dev - sorry if this issue might be dumb :)

**Comment by pnxenopoulos** [comment]
Hi Martin,

No worries! Sorry to hear you're facing some troubles. A few questions/suggestions:

- Try upgrading by doing `pip install --upgrade --pre awpy`, I actually just pushed the `v2.0.0b4` update
- Could you link to a specific demo if the problem persists?

**Comment by martin1896** [comment]
Thanks for your quick answer. 

I upgraded, but still get the `v2.0.0b2`, which I had before (I guess, because I installed it just yesterday). 

I used some demos from scrimmage matches (older and new ones) and the Ancient demo from this match: https://www.hltv.org/matches/2374312/natus-vincere-vs-saw-iem-cologne-2024 - all demos failed with the same error.

**Comment by martin1896** [comment]
Update: I tried to use your framework locally on my windows pc and everything works fine (on Windows I get `v2.0.0b4`). Maybe there is some issue with my python/pip installation on my MacBook.

**Comment by pnxenopoulos** [comment]
Thanks for the note, I'll do some more testing on a mac. You can upgrade to the most recent version of awpy with `pip install --upgrade --pre awpy`.

Closing the issue for now, but please feel free to reopen or create a new issue if anything arises!
